site_name: ns-atmosphere
nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting_started.md
  - Pipeline: pipeline.md
  - Structure: structure.md

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.css
extra_head_scripts:
  - |
    window.MathJax = {
      tex: {
        inlineMath: [ ['$', '$'], ['\\(', '\\)'] ],
        displayMath: [ ['$$', '$$'], ['\\[', '\\]'] ]
      }
    };